name: betting_agent
channels:
  - defaults
dependencies:
  - aom=3.6.0=hcec6c5f_0
  - blas=1.0=openblas
  - blinker=1.9.0=py310hecd8cb5_0
  - bottleneck=1.4.2=py310hf3fd67a_0
  - brotli-python=1.0.9=py310h6d0c2b6_9
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cairo=1.16.0=h08824b9_6
  - click=8.2.1=py310hecd8cb5_0
  - contourpy=1.3.1=py310h1962661_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h6c40b1e_0
  - expat=2.7.1=h6d0c2b6_0
  - flask=3.1.0=py310hecd8cb5_0
  - fontconfig=2.14.1=h269ac6a_3
  - fonttools=4.55.3=py310h46256e1_0
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.10=haf1e3a3_0
  - gettext=0.21.0=h4e8c18a_2
  - graphite2=1.3.14=he9d5cce_1
  - harfbuzz=10.2.0=h060d35a_1
  - icu=73.1=hcec6c5f_0
  - itsdangerous=2.2.0=py310hecd8cb5_0
  - jinja2=3.1.6=py310hecd8cb5_0
  - joblib=1.5.1=py310hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - kiwisolver=1.4.8=py310h6d0c2b6_0
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=h6d0c2b6_0
  - libavif=1.1.1=h46256e1_0
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h46256e1_0
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libglib=2.84.2=heb90364_0
  - libiconv=1.16=h6c40b1e_3
  - libopenblas=0.3.29=h3f8574a_0
  - libpng=1.6.39=h6c40b1e_0
  - libtiff=4.7.0=h2dfa3ea_0
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=h5048363_2
  - lz4-c=1.9.4=hcec6c5f_1
  - markupsafe=3.0.2=py310h46256e1_0
  - matplotlib=3.10.0=py310hecd8cb5_0
  - matplotlib-base=3.10.0=py310h919b35b_0
  - ncurses=6.5=h923df54_0
  - numexpr=2.11.0=py310h20bc273_0
  - numpy=1.26.4=py310hf6dca73_0
  - numpy-base=1.26.4=py310hd8f4981_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.0.17=hee2dfae_0
  - packaging=25.0=py310hecd8cb5_0
  - pandas=2.3.1=py310hebe84f7_0
  - pcre2=10.42=h9b97e30_1
  - pillow=11.3.0=py310h25d8182_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=hb254d66_0
  - pyparsing=3.2.0=py310hecd8cb5_0
  - python=3.10.18=hc958d9f_0
  - python-dateutil=2.9.0post0=py310hecd8cb5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py310hecd8cb5_0
  - pyyaml=6.0.2=py310h46256e1_0
  - readline=8.3=h49f2429_0
  - scikit-learn=1.7.1=py310h20cdf89_0
  - scipy=1.15.3=py310h97975f9_0
  - seaborn=0.13.2=py310hecd8cb5_3
  - setuptools=78.1.1=py310hecd8cb5_0
  - six=1.17.0=py310hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - threadpoolctl=3.5.0=py310h20db666_0
  - tk=8.6.15=h3a5a201_0
  - tornado=6.5.1=py310h46256e1_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py310h46256e1_1
  - werkzeug=3.1.3=py310hecd8cb5_0
  - wheel=0.45.1=py310hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=haf1e3a3_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
  - pip:
      - alembic==1.17.2
      - bottle==0.13.4
      - cloudpickle==3.1.2
      - colorlog==6.10.1
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - flask-cors==6.0.1
      - fsspec==2025.12.0
      - greenlet==3.3.0
      - gymnasium==1.0.0
      - mako==1.3.10
      - mpmath==1.3.0
      - networkx==3.4.2
      - optuna==4.6.0
      - optuna-dashboard==0.20.0
      - playwright==1.56.0
      - pyee==13.0.0
      - sqlalchemy==2.0.44
      - stable-baselines3==2.4.1
      - sympy==1.14.0
      - tomli==2.3.0
      - torch==2.2.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - xgboost==3.1.2
prefix: /Users/henrylukewille/opt/anaconda3/envs/betting_agent
