environment:
  apply_gameday_filter: false
  bet_amount: 10.0
  confidence_scaling_mode: quadratic
  confidence_threshold: 0.55
  draw_penalty_multiplier: 1.5
  kelly_fraction: 0.25
  max_bet_amount: 30
  max_bet_rate: 0.3
  min_edge_required: 0.05
  min_gameday: 4
  no_bet_reward_multiplier: 0.5
  reward_shaping: balanced
  use_betting_odds: true
  use_kelly_criterion: true
model:
  algorithm: DQN
  dqn:
    batch_size: 64
    buffer_size: 100000
    exploration_final_eps: 0.02
    exploration_fraction: 0.3
    exploration_initial_eps: 1.0
    gamma: 0.95
    learning_rate: 0.0001
    learning_rate_finetune: 1.0e-05
    learning_rate_incremental: 5.0e-06
    learning_starts: 5000
    target_update_interval: 500
    tau: 1.0
  policy_kwargs:
    net_arch:
    - 256
    - 256
    - 128
paths:
  checkpoints_dir: /Users/henrylukewille/Desktop/Betting_Agent_WebApp/meta_combined_results/meta_balanced_20251121_144304/run_S2024_Seed1337_C0.55_Edge0.05_Rate0.3_Scale-quadratic_Kelly_balanced/checkpoints_dir
  data_dir: data/processed
  logs_dir: /Users/henrylukewille/Desktop/Betting_Agent_WebApp/meta_combined_results/meta_balanced_20251121_144304/run_S2024_Seed1337_C0.55_Edge0.05_Rate0.3_Scale-quadratic_Kelly_balanced/logs_dir
  models_dir: /Users/henrylukewille/Desktop/Betting_Agent_WebApp/meta_combined_results/meta_balanced_20251121_144304/run_S2024_Seed1337_C0.55_Edge0.05_Rate0.3_Scale-quadratic_Kelly_balanced/models_dir
  raw_data_dir: data/raw
  results_dir: /Users/henrylukewille/Desktop/Betting_Agent_WebApp/meta_combined_results/meta_balanced_20251121_144304/run_S2024_Seed1337_C0.55_Edge0.05_Rate0.3_Scale-quadratic_Kelly_balanced/results_dir
training:
  fine_tune_gamedays: 8
  finetune_timesteps: 100000
  global_seasons:
    end: 2023
    start: 2016
  global_timesteps: 1000000
  incremental_learning: true
  incremental_timesteps: 10000
  target_season: 2024
